vectorniner/GitLab

rpgGame.c

fixed typos, added room 25

---

rpgGame.c

Push Room 18 to master.

---

rpgGame.c

room 11 added

---

rpgGame.c

-Health System implemented
-Storytelling fixed

Added Room 16

---

rpgGame.c

Room 16 contains various loops.

Room 16 "Complete" - dguevaracolocho1

---

rpgGame.c

Room 3  (4/2/18)

---

rpgGame.c

New version

---

rpgGame.c

SALVADOR RODRIGUEZ
RAMEN8R
STUDENT ID 204145864

ROOM 19-ADDED FILE PROCESSING ASPECTS

---

rpgGame.c

Almost done other direction will use other techniques

Update rpgGame.c missing file manipulation and arrays

---

rpgGame.c

removed conflict with ; in line 616
Changed main to int

Room 20 //Cesar Gutierrez

---

rpgGame.c

Sean de Silva room 15

---

rpgGame.c

ROOM # 3 -- Elthon Cisneros
No Conflicts.
Added Switches, Character Manipulation (toupper), for loop, while loop, constant variables, arrays, RANDOM (numbers), if/else statements, scanning characters,

Elthon FINAL version; No Conflict

---

rpgGame.c

I added 2 separate functions, pointer and switch statement.
Thank you.

My last version

---

rpgGame.c

Added mine field level in room 12
Added grading for the amount of guesses for Guess the number game in room 12
Completed the Typing Challenge game in room 12
Completed the Roll the Dice game with pointers in room 12

Added room 12

---

rpgGame.c

Room 16 Finalized Game 

---

rpgGame.c

Finished Room 18 - Joseph

---

rpgGame.c

Revert "Update rpgGame.c"

---

rpgGame.c

Reverts vectorniner/GitLab#60
Undeclared f
You must compile and run yourself before you make a pull request.... does not compile

Revert "File and string mods added, format issues fixed"

---

rpgGame.c

used preexisting Name variable instead of asking again
deleted empty puts statement

room 10 update

---

rpgGame.c

- Fixed a bug for a function write() 
Changed write(void) to writte(void)
- Added file manipulation to Room 6.

Updated Room 6

---

rpgGame.c

adding room 4

---

rpgGame.c

Diana Guevara-Colocho Room 16

---

rpgGame.c

Had to comment out a prototype, function, and function call from another room as it was not compiling

Airrion Young - adds Random Numbers, Strings, Arrays

---

rpgGame.c

Some cases had a lack of ending brackets.

Project Compiles now.

---

rpgGame.c

- Previous pull request ignored changes to room 6.

Reupdated Room 6

---

rpgGame.c

Updated Room 4
